/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'bedroom' : IDL.Null,
  'office' : IDL.Null,
  'livingRoom' : IDL.Null,
  'dining' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'review' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'addToFavorites' : IDL.Func([IDL.Text], [], []),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getFavoriteProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'bedroom' : IDL.Null,
    'office' : IDL.Null,
    'livingRoom' : IDL.Null,
    'dining' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'review' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'addToFavorites' : IDL.Func([IDL.Text], [], []),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getFavoriteProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromFavorites' : IDL.Func([IDL.Text], [], []),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };