/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'bedroom' : null } |
  { 'office' : null } |
  { 'livingRoom' : null } |
  { 'dining' : null };
export interface Product {
  'id' : string,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export interface Testimonial {
  'id' : string,
  'customerName' : string,
  'review' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[Product], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'addToFavorites' : ActorMethod<[string], undefined>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getFavoriteProducts' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'removeFromFavorites' : ActorMethod<[string], undefined>,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];